### ISSUE TITLE
erase-data could delete the subject's data, aside from deleting his cryptographic key

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#113]
Very low priority

**Comment by sindelio** [comment]
For now let's leave it in the backlog. I will try to make a good case whether we should delete the data or not

**Comment by sindelio** [comment]
Some thoughts on this:

Pros:
- We would adhere more to the "right to be forgotten". Although deleting the decryption key effectively means the data was lost, there still exists traces of it, even if encrypted.
- A minimal memory usage improvement. But insignificant really, unless the personal data goes to MB size, which is not happening. Also, considering we still will keep the ID of the subject for record/audit reasons, we would be deleting only the personal_data column.
- It's a simple change and a test for it.

Cons:
- The system is functional the way it is. There's more important features to invest on right now.

My opinion is that this should wait until all rights are properly implemented, along with their UIs. 
This will most likely sit int the backlog for a while xD

**Comment by Jakedavies** [comment]
We discussed this and decided it is good the way it is.

**Comment by sindelio** [comment]
I think we should delete the data, and it's just a query (3 lines) in the subjects service. It makes up for more transparency, and leaves no trace of the subjects data
