### ISSUE TITLE
Improve styling for default components

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#127]
Components such as forms, buttons, badges, for example, can be built from Bulma, without importing the whole stack. There are 2 ways here: 1) using directly Bulma and override specific components and styles (using both modular[1] and custom configuration[2]) or 2) Start defining these generic components as part of admin boilerplate core style guide [3]

[1] https://bulma.io/documentation/overview/modular/
[2] https://bulma.io/documentation/overview/customize/
[3] https://medium.com/@perezpriego7/css-evolution-from-css-sass-bem-css-modules-to-styled-components-d4c1da3a659b

**Comment by fjcero** [comment]
@juanmnl I merged the combination of `admin` with `admin-designs`. Workflow is the same, beyond you can notice some differences, you can start working with `yarn start` without problems.

**Comment by fjcero** [comment]
Oh, components are now inside "src/components/core/`

**Comment by juanmnl** [comment]
<img width="579" alt="screen shot 2018-06-18 at 7 25 16 pm" src="https://user-images.githubusercontent.com/699945/41569137-25d32dca-732f-11e8-9bf0-0052ab4c2be6.png">
