### ISSUE TITLE
Implement basic "update requests" functionality on

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#134]
The first part of this is creating a way to intitiate an update request
- [x] Come up with a an update-request schema
- [x] add endpoint for initiating an update request
- [x] endpoint for listing the status of update requests for the user
- [ ] tests

I imagine the schema looks something like this(im sure i missed some stuff..

integer: id
integer: subject_id
text: request_reason
timestamptz: created_at
status: ENUM['APPROVED', 'DISAPROVED']

**Comment by sindelio** [comment]
These update requests are for the subject's data/credentials or the manager's credentials?

**Comment by sindelio** [comment]
Closes #21
