### ISSUE TITLE
HTTP 500 error on wrong payload during login

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#146]
**Steps to reproduce:**
Make a request to `/api/management/users/login` using an incorrect payload (ex. `email` instead of `username`

**Expected result:**
HTTP Error 400 (Bad Request)

**Actual result:**
HTTP Error 500 (Internal Server Error)

**Comment by Jakedavies** [comment]
Check the other /users endpoints to make sure they have validation too
