### ISSUE TITLE
Right to restriction of processing

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#147]
Art. 18 GDPR - Right to restriction of processing

"1. The data subject shall have the right to obtain from the controller restriction of processing where one of the following applies:
(a) the accuracy of the personal data is contested by the data subject, for a period enabling the controller to verify the accuracy of the personal data;
(b) the processing is unlawful and the data subject opposes the erasure of the personal data and requests the restriction of their use instead;
(c) the controller no longer needs the personal data for the purposes of the processing, but they are required by the data subject for the establishment, exercise or defence of legal claims;
(d) the data subject has objected to processing pursuant to Article 21(1) pending the verification whether the legitimate grounds of the controller override those of the data subject.
2. Where processing has been restricted under paragraph 1, such personal data shall, with the exception of storage, only be processed with the data subject’s consent or for the establishment, exercise or defence of legal claims or for the protection of the rights of another natural or legal person or for reasons of important public interest of the Union or of a Member State.
3. A data subject who has obtained restriction of processing pursuant to paragraph 1 shall be informed by the controller before the restriction of processing is lifted."

This one can be a big deal, since it affects legal claims and disputes. Basically the subject can request that the processors stop using his data completely or partially. The controller may also stop the processing of the subject's data by the processors, if it is unlawful or it has lost its purpose.
Note that the right to object is a case of the right to restriction, the former consisting of any and every processing being stopped by the controller and all processors.
The right to restriction of processing has granularity regarding which processor can process the data, if the controller can process the data, which data can be processed, and for what purpose.

**Comment by sindelio** [comment]
Subject flow:

1. Subject logs into his account
2. Goes to his data area / dashboard
3. Clicks in a button to restrict the processing of his data
4. A new window / slider shows up with information regarding what he can restrict
5. Two panels show up below the window / slider. 
a. Panel 1: Restrict what can be done with his data. It's a checkbox list with: email comms and newsletter, direct marketing, research, ( more suggestions?)
b. Panel 2: Restrict who can process his data. A list with the processors that he gave consent is displayed and he can check each processor.
c. (For the future) Panel 3: the subject can specify a period of time in which his data can be processed.

**Comment by sindelio** [comment]
System flow:

1. The front-end makes a request to the cg API for a restriction of processing. This request can be a restriction of actions (what) or a restriction of particular processors (who)
2. The API request is processed by the back-end, which then updates the DB with the new state for the subject data. There should be a boolean list of possible status for the subject's data regarding what actions can be done with his data. This list can be inside the 'subjects' table, alongside the 'personal_data' column. Or it can be in a separated table. Initially I'd go with the first approach. The subject data state is then updated.
3. The back-end requests the restriction to be recorded in the blockchain. A smart contract function is called, which will then update a boolean list of actions that a processor can execute with the subject's data. This list of bolleans is the same that's stored in the DB. The smart contract needs two functions, one to restrict the actions that can be done with the subject's data (what) and other to restrict particular processors (who). Both these functions will fire events in the smart contract, which will be recorded in a transaction, inside a block in the blockchain.

**Comment by sindelio** [comment]
Actionables (each will have a separate task)

 UI:
- [ ] Button to initiate the right to restriction inside the subject's data area / dashboard
- [ ] Window / slider with information regarding the right to restrict
- [ ] Panel for the restriction of certain actions. It contains a checkbox list with the following: email communication and newsletter, direct marketing, research[, ?]
- [ ] Panel for the restriction of particular processors. All processors that have the subject's consent are displayed and he can check each of them for restriction.

Back-end API:
- [ ] Endpoint and tests for restriction of certain actions: '/api/subject/restrict/actions'
- [ ] Endpoint and tests for restriction of certain processors: '/api/subject/restrict/processors' (Very similar to the update processors endpoint)
- [ ] Endpoint to list the restricted and allowed actions that a processor can execute with the subject's data: '/api/subject/restrict/list-actions'. This endpoint is called before the '/api/subject/restrict/actions' in the UI to display the current subject's restricted actions.

Smart contract:
- [ ] List of actions that can be restricted by the subject. Will be a boolean property of each subject. 
- [ ] Function and event to restrict certain actions on a subject's data.
- [ ] Function and event to restrict certain processors.

**Comment by Jakedavies** [comment]
Do we treat restrictions as a specific concept on the backend + smart contract, or can we come up with a way to do it as a single state tree? I mean, rather than applying the restrictions over top of the consent to work out what the users GDPR consent state is, is there a nicer way to do it by just maintaining one set of records  and treating a restriction of processing as the removal of consent to processing?

Not sure if that made sense.. let me know if I can expand anymore

**Comment by sindelio** [comment]
I think I understand what you mean. The complete removal of consent configures an objection, so we will do that for the right to object. The right to restrict is inherently granular. Assuming that a state tree is the set of possible states a subject's data can fall under, then we will have a state tree whose possible states are determined by the union between the subject's data status and his restricted actions. And we are also applying the restrictions on top of the consent. Let's discuss this further Monday, there's some questions and trades that need attention from the team

**Comment by sindelio** [comment]
The back-end is finished, now we have to work on the front-end support for this right.
