### ISSUE TITLE
Add absolute module resolution for admin project

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#158]
We can try using https://github.com/tleunen/babel-plugin-module-resolver to have absolute paths to modules in our admin project. Example:

`@cg/components` > `./src/components`

Then we wouldn't have imports like:

```
import Sidenav from '../../components//Sidenav';
import Card from '../../components/core/cards/dashboard/Card';
import session from '../../helpers/Session';
import Logo from '../../assets/logo.png';

```

but these instead:

```
import Sidenav from '@cg/components/Sidenav';
import Card from '@cg/ui/dashboard/Card';
import session from '@cg/helpers/Session';
import Logo from '@cg/assets/logo.png';
```

That can break jest (see [solution](https://simonsmith.io/simplifying-module-resolution-with-babel-or-webpack/)).

**Comment by fjcero** [comment]
👍 I love that for refactoring. Also helps splitting imports into packages if necessary in the future, without major difficulties.
