### ISSUE TITLE
Design the blockchain event auditing tool

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#16]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Show the top 3 most important informations from the blockchain events in the Admin UI.

**Describe alternatives you've considered**
None.

**Additional context**
Define the top 3. @sindelio @fjcero @juanmnl

**Comment by Jakedavies** [comment]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jakedavies](https://github.com/Jakedavies)**
_Monday May 14, 2018 at 23:20 GMT_

----

Juan will need to add this to the UI first

**Comment by Jakedavies** [comment]
![39851679-2b0ce960-53cd-11e8-8cd8-2f3cce4509e0](https://user-images.githubusercontent.com/3431461/41166494-2f4c5be8-6af5-11e8-9917-995ee81d4d72.png)

**Comment by maksymilian-majer** [comment]
@juanmnl this is in Done, but where's the design?

**Comment by juanmnl** [comment]
@maksymilian-majer didn't move this one. There was only a concept, but never finished the design with all the software issues I had. But can get back to it.

**Comment by Nelrohd** [comment]
Top 3 infos
@sindelio @fjcero opinion? suggestions?

**Comment by segoddnja** [comment]
I think the plain list of events is not really useful. I think about stacked area chart with ability to expand any event type as listing. But, as it looks to me there is an event type which always will have highest percentage - access data event. So, all other events could be invisible most of the time on this chart.

Another useful feature is to filter events by subject.

**Comment by sindelio** [comment]
Most important infos:

event: String - The event name.
args: Object - The arguments coming from the event.
address: String, 32 Bytes - address from which this log originated.
blockNumber: Number - the block number where this log was in. null when its pending.

Initially I think we should show the blocks that were removed as well. So even if the "removed" boolean is true, we should still list that event for clarity.

**Comment by fjcero** [comment]
@juanmnl looks really neat!
