### ISSUE TITLE
The management/subjects.controller has some mutatey-maps in it that should be fixed

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#165]
This block:
```
  async listSubjects(req, res) {
    const subjectsPage = await this.subjectsService.listSubjects(req.query.page);
    subjectsPage.map(subject => {
      // Covers the subjects data with '*'s
      _.mapObject(subject, (value, key) => {
        subject[key] = coverString(value);
      });
    });
    return res.json(subjectsPage);
  }
```

eslint is upset because we aren't returning, which led me to discover that both maps are mutating the inputs which is confusing and bug prone. We should switch this to be more in line with more standard map function use, and return new objects that we build up.

**Comment by sindelio** [comment]
I'm on this. I see, mutating objects all the time really is more bug prone than creating new ones.
The major benefit of mutating the object itself is performance regarding memory, but that's not an issue for our project xD
It's basically a trade between code readability, maintainability and bug probability vs memory performance
