### ISSUE TITLE
Allow configuration of frontend URLs in admin

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#175]
**Is your feature request related to a problem? Please describe.**
For our demo front-end it's not relevant if the URL is hardcoded, but if we want to allow users to use our front-end image that hosts a static site, then we have to provide some way to configure it.

**Describe the solution you'd like**
@sindelio  @fjcero Please complete.

**Describe alternatives you've considered**
None.

**Additional context**
It is in the `config.js` file.

**Comment by fjcero** [comment]
This is related to the admin config in general and how it is deployed. Since Admin uses an API, this URL could be dynamic based on customers configuration. Will delete it, and a better description will be added when we address deploy and documentation.
