### ISSUE TITLE
Improve "request to be forgotten" flow

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#176]
**Description:**

As a subject when I go to the demo front-end and want to request to erase my data I have to click a button.

After subject clicks the button the system needs to show them a warning message, that when they erase thair data all the share URLs will become inactive and they will no longer be able to retrieve their data from our system.

**Acceptance criteria**

- [ ] Add confirmation when clicking the "request" button
- [ ] Add a test to cover this use case
- [ ] Shared data should be unavailable after accepting deletion

**Steps:**

1. In `demo-frontend` app
2. I login as a registered user
3. Click the "request to be forgotten" button
4. There should be a confirmation message shown with "Are you sure you want to request erasure of your data?"
5. If the user goes to the `/shares` page should appear all shared data as inactive (or deleted)

**Comment by segoddnja** [comment]
@fjcero You promised to add more details to the ticket description

**Comment by fjcero** [comment]
We should make sure that when the user requests to delete his data, all the date shared and listed in the `/shares` (in the demo) are consistent with the deletion. Also, the modal triggered right now have some considerations that are not quite precise like the checkboxes doing nothing in the flow.
