### ISSUE TITLE
docs architecture image is not deploying

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#177]

**Comment by maksymilian-majer** [comment]
I see there are forbidden results:

![screen shot 2018-06-20 at 17 44 38](https://user-images.githubusercontent.com/1215868/41669268-b5ff3ece-74b1-11e8-8b63-55c084af6cd9.png)

**Comment by Jakedavies** [comment]
Working with ops to work this out, diagram appears to be on the server but denying requests... Ops isn't sure how that could happen but they are looking into it.
