### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#182]
`react-form` is a way to abstract form control, is not hardly opinionated but it needs more work to allow reusable components and facilitate implementation.

Some of the key points are:

- Handle Errors, for now global, but will be nicer to allow inline errors as well
- Styling should be applied by default
- A schema could be specified (probably a combination with `react-jsonschema-form`)

Some interesting reads on how do forms without having to use redux
- https://moduscreate.com/blog/reactjs-form-validation-approaches/
- https://medium.com/javascript-inside/some-thoughts-on-forms-in-react-9ca2d9078c20

Libs proposed/used:
- https://github.com/mozilla-services/react-jsonschema-form
- https://github.com/react-tools/react-form

**Comment by maksymilian-majer** [comment]
@fjcero so far I've used the forms from @juanmnl for issue #174 which is in progress, so let's refactor later

**Comment by fjcero** [comment]
@maksymilian-majer `react-form` was renamed to `informed` -> https://joepuzzo.github.io/informed

Either way, no major changes are required to use this library, and I'm researching a way to test forms in a more sustainable way instead of repeating code by each form implementation. Probably abstracting the generic Form in a `common` component will be a good idea. I will like to chat with you before working further in this task

**Comment by maksymilian-majer** [comment]
I see we naturally went to use react-forms and I created an issue to migrate to informed (#209)
Can this be closed down?

**Comment by fjcero** [comment]
Yeah, let’s continue the migration in #209.
