### ISSUE TITLE
Handling error/success notifications

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#195]
- [x] password successfully change
- [x] user successfully registered
- [x] user successfully deleted
- [x] fetch errors in case of all unhandled errors in the above methods
- [x] deleting user (when #194 closed)

Sometimes there can be errors or success notifications that we could show to the user "detached" from the UI. Like after successful password change a nice popup would be welcome. 

We could use something like:
https://fkhadra.github.io/react-toastify/
https://tomchentw.github.io/react-toastr/
https://github.com/jesusoterogomez/react-notify-toast

Let's have the toasts show from top-center.

**Comment by maksymilian-majer** [comment]
@juanmnl any thoughts on this?

**Comment by fjcero** [comment]
@maksymilian-majer I believe we can start using the simplest library and then @juanmnl can improve the styling. If you build kind of a reusable presentational component inside `core` will be simpler to edit styles later, just as an idea.

**Comment by maksymilian-majer** [comment]
@Jakedavies maybe you would just handle this also in the `internalFetch` in case of all unknown 500 errors?
