### ISSUE TITLE
Confirmation dialog UI

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#198]
We need some kind of confirmation dialog (ideally using some well established React package) for tasks like #194.

**Comment by maksymilian-majer** [comment]
@juanmnl I have added some simple confirmation in #228 (PR for #194). You can take a look at it.

**Comment by juanmnl** [comment]
Non Blocking Dialog example
<img width="1371" alt="screen shot 2018-07-09 at 9 58 41 am" src="https://user-images.githubusercontent.com/699945/42458090-ca08c91a-835e-11e8-882d-159f5a7cf2b0.png">
