### ISSUE TITLE
Security tests on the smart contract

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#2]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sindelio](https://github.com/sindelio)**
_Friday Apr 06, 2018 at 18:47 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/28_

----

Have to test the smart contract against the most common attacks, such as:

- Reentrancy attacks
- Gas loop
- Overflows

**Comment by sindelio** [comment]
There are some possible attacks to smart contracts that we should at least look into. Overflows and underflows are an example, which can break the contract in production. We should not close this yet
