### ISSUE TITLE
Investigate what restriction of processing means?

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#20]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jakedavies](https://github.com/Jakedavies)**
_Monday May 14, 2018 at 23:29 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/192_

----

I was going to create tasks to add restriction of processing to the smart contract and API side but want to chat with you guys about what that will actually mean in terms of the nodes and what they can do.

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Tuesday May 15, 2018 at 15:50 GMT_

----

Lets just add a restricted state to blockchain – meaning we can only process data of the subject for legal / tax reasons and not for other marketing kind of stuff.

**Comment by Jakedavies** [comment]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sindelio](https://github.com/sindelio)**
_Tuesday May 15, 2018 at 17:53 GMT_

----

From the blockchain perspective I think it's just states being updated and events fired, as we spoke in the stand today. If any new ideas show up please let me know

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Friday May 18, 2018 at 12:46 GMT_

----

That's covered here: https://gdpr-info.eu/art-16-gdpr/
The process of candidate applying for update and us updating the data will cover it well enough IMO.

**Comment by sindelio** [comment]
Depends on #140

**Comment by sindelio** [comment]
See #100
