### ISSUE TITLE
Allow user to see and manage own profile

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#208]
Related to #211.

There is a section called Profile that should allow the current user to edit the profile. Since this is related to the Controller, probably it makes more sense to have kind of an Organization Team Management sections instead of just the plain profile

**Comment by segoddnja** [comment]
At this moment admin users have only 2 attributes - name and password. So I am not sure what info to display on profile page as user name is on the top right corner of the screen. Also it is not clear what can be editable here. There is ability to update password from users list page http://pix.toile-libre.org/upload/original/1532515571.png So, just place the same button on the profile page?

@fjcero Can you clarify this?

**Comment by segoddnja** [comment]
As we discussed it a bit before, I think we can close it. @fjcero can you confirm that?

**Comment by fjcero** [comment]
Yup @segoddnja lets close it, is not necessary for now.
