### ISSUE TITLE
A user is supposed to be able to update their information

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#21]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jakedavies](https://github.com/Jakedavies)**
_Monday May 14, 2018 at 23:31 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/193_

----

"Right to rectify data"

This one is sort of weird... as a basic implementation we could basically just give crud access to the data we store on a user without concern for what happens for consumers of the data. In the real world allowing users to update data we have collected on them seems pretty scary.

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Tuesday May 15, 2018 at 12:56 GMT_

----

I have some idea – let's discuss this.

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Tuesday May 15, 2018 at 15:45 GMT_

----

We intend to add this as an approval based process, ex:

The subject goes to a data update form, and enter new data. Then they submit this as an update request and it waits for approval from controller/processor staff member. We will need appropriate flow implemented by the contract.

**Comment by Jakedavies** [comment]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sindelio](https://github.com/sindelio)**
_Tuesday May 15, 2018 at 17:51 GMT_

----

Ok, I'm still on the tests, but probably tomorrow or Thursday I can be on this. Starting in the smart contract amd going up to the endpoints / tests

**Comment by Jakedavies** [comment]
Adding some notes here:

Needed:
- Backend functionality for queuing submitting updates for approval
- API endpoints for managing pending updates
- API endpoint for requesting updates
- Frontend interface for approving updates
- Frontend interface for requesting a data update

Maybe: 
- Functionality for notifying users about data update status changes

**Comment by sindelio** [comment]
Depends on #140
