### ISSUE TITLE
Refactor internalFetch to handle api errors nicely

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#225]
@sindelio Please fill it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fjcero** [comment]
`internal-fetch` is used by the admin and right now covers the scenario that if an error happens a toast is triggered. So far, is covered, a more specific scenario should be described in the future (if any)
