### ISSUE TITLE
Update subject data status in the front-end

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#248]
The subject Data Statuses were changed in the back-end:

notShareable => unconsented
shareable => consented

We should update those in the front-end too so that everything works nicely

**Comment by fjcero** [comment]
The frontend only has an array of "labels" for each type of consent status. So far, I checked that we are only using this in the frontend demo to map status with a humanly understandable label. If the index of status remains, that the only needed, since we are not matching by keys.

**Comment by Jakedavies** [comment]
Lets change the strings in the frontend code so it matches the backend even if its not needed
