### ISSUE TITLE
Race condition between give-consent and approve-rectification endpoints

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#256]
**Describe the bug**
A race condition was happening in the give-consent and approve-rectification endpoints, in which the processor reacted to the event fired and tried to get the new subject's data from the controller, but the controller wasn't done updating his DB yet.

**To Reproduce**
@sindelio Please complete

**Expected behavior**

**Screenshots**

**Additional context**
Closes #233. We will probably need checkpoints in the transactions happening. Also the erasure endpoints need to be checked for this racing condition as well.

**Comment by Nelrohd** [comment]
@sindelio fill the to the reproduce

**Comment by sindelio** [comment]
We already fixed this too.
