### ISSUE TITLE
Create tests for transactions that have inter dependent DB and blockchain actions 

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#258]
We need to set tests for the possible scenario in which blockchain updates and database updates don't happen as a transaction, which they should be.
The checkpoints seem to work with `transaction.commit()` what we need to do is write tests that fail the blockchain code and expect that the transaction has rolled back.
Related to #256

**Comment by maksymilian-majer** [comment]
@sindelio I think that's no longer the case and we need to figure out some other revert strategy

**Comment by Nelrohd** [comment]
I close it, @sindelio feel free to re-open and modify the description following our issue templates.
