### ISSUE TITLE
Should we fire an event when a user requests/downloads his data? 

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#26]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sindelio](https://github.com/sindelio)**
_Friday May 18, 2018 at 17:10 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/221_

----

My first thought is yes, because it can be useful for auditing purposes in the future

**Comment by sindelio** [comment]
Related to #79

**Comment by sindelio** [comment]
We fire events when a subject

- gives consent
- access his data
- erases his data
- restricts the actions with his data
- rectifies his data

Why not fire an event when he downloads/shares his data?
