### ISSUE TITLE
Add nice styling for tabs and pagination

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#264]
**Is your feature request related to a problem? Please describe.**
We are currently using the default styles of a tab and pagination library. They should be styled to match the current styling of the app.

**Describe the solution you'd like**
A cleaner and more modern approach to styles.
- [x] tabs
- [x] pagination
- [ ] better handling of row rendering (workaround in rectifications using two content divs)

**Describe alternatives you've considered**
None.

**Additional context**
See #261 PR for screenshots of what needs styling.

**Comment by juanmnl** [comment]
Tab concept

<img width="629" alt="screen shot 2018-07-31 at 10 09 54 am" src="https://user-images.githubusercontent.com/699945/43468579-ff8f8d88-94a9-11e8-9b76-c5d0c4be0a92.png">

Pagination Concept

<img width="400" alt="screen shot 2018-07-31 at 10 10 02 am" src="https://user-images.githubusercontent.com/699945/43468603-0c9f535a-94aa-11e8-9762-c6210b7a90d3.png">
