### ISSUE TITLE
Management subjects listing endpoint needs pagination

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#28]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jakedavies](https://github.com/Jakedavies)**
_Tuesday May 22, 2018 at 15:22 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/229_

----

add a parameter to the subject listing endpoint that adds `?page=1`

**Comment by Jakedavies** [comment]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jakedavies](https://github.com/Jakedavies)**
_Tuesday May 22, 2018 at 15:25 GMT_

----

sort by id's for now so your pages are consistent

**Comment by sindelio** [comment]
ex:
`GET /api/management/subjects` returns:
```{
    pageCount: 3
    subjects: [item1, item2]
}```
(edited)
`GET /api/management/subjects?page=2` returns:
```{
    pageCount: 3
    subjects: [item3, item4]
}```
(edited)
`GET /api/management/subjects?page=3` returns:
```{
    pageCount: 3
    subjects: [item5]
}```

**Comment by Jakedavies** [comment]
blocked by #68
