### ISSUE TITLE
Blank out subject data on /management/subjects/list

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#29]
<a href="https://github.com/Jakedavies"><img src="https://avatars1.githubusercontent.com/u/3431461?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Jakedavies](https://github.com/Jakedavies)**
_Tuesday May 22, 2018 at 15:23 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/230_

----

we should be blanking out the data on this endpoint
{ name: 'j***** d**** ' }

**Comment by sindelio** [comment]
Starting this task, any suggestion of material/framework on it?

**Comment by sindelio** [comment]
Is it ok if only the first letter of each word is shown?
Like this:
```
Sindelio Lima => S******* L***
email: s*******@clevertech.biz
```
