### ISSUE TITLE
Define domain entities and factories

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#291]
**Is your feature request related to a problem? Please describe.**
Avoid defining properties for each Type of entity we have in the UI.

**Describe the solution you'd like**
Format DTO to entities that match the frontend is to create constructors that allow formatting a specific set of data in a valid domain entity. This also is one approach to have immutable objects if we want to push forward for that in the future.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Nelrohd** [comment]
@fjcero Can you give an example of what you want to do?

**Comment by fjcero** [comment]
We can push forward with prop-types for now. I defined global types some time ago, need to continue working on that.
