### ISSUE TITLE
Add tests to CG Demo implementation

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#307]
**Is your feature request related to a problem? Please describe.**
Add tests to CG demo implementation.

**Describe the solution you'd like**
- [x] Add Jest configuration.
- [x] Add prop-types to all the components.
- [ ] Shout warnings on non-conventional code present.
- [ ] Add tests for Containers and Elements.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Nelrohd** [comment]
@fjcero The work required seems to be quite big, do you think it would be worth it to split the work into smaller tickers (like 4)?

**Comment by fjcero** [comment]
Yup, makes sense. Also, some of them are already done so will be cleaner.

**Comment by fjcero** [comment]
Will create smaller tasks for the unresolved ones
