### ISSUE TITLE
Integrate blockchain events UI

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#320]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The feed of blockchain events should be added to our main dashboard.

**Describe alternatives you've considered**
None.

**Additional context**
UI details in #16

**Comment by sindelio** [comment]
Need help with this Dmytro?

**Comment by segoddnja** [comment]
I don't think so.

**Comment by segoddnja** [comment]
@sindelio Actually I did try to find anything related to the events log in the code base. I found nothing. I don't see table in the database, I don't see method in smart contract. Can you point me to the service I can use to retrieve events from the log, preferably with ability to apply filters, sort and pagination?

**Comment by sindelio** [comment]
Let's pair program today, I will show you

**Comment by segoddnja** [comment]
I won't have time as I finish work day right after standup, can you just point me to the code?
