### ISSUE TITLE
Don't redirect if request fails

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#337]
**Describe the bug**
The new processors does not have an address, so the request fails. Currently the request fails, but user is still redirected. The subject does not exist. @fjcero Please complete or modify.

**To Reproduce**
1. login to admin.
2. add a new processor.
3. login to front-end demo.
4. consent to all processors.

**Expected behavior**
We should handle error gracefully and show some error message.

**Screenshots**
None.

**Additional context**
None.

**Comment by Nelrohd** [comment]
Let's split it @fjcero .

**Comment by Nelrohd** [comment]
@juanmnl Please add information about why subject should know which processor use his data.

**Comment by juanmnl** [comment]
A user should be able to know and review which processor is using it's data. May not be needed 99.99% of the time, but it should be accessible for the user who wants to know/control/change.

Use case:
User doesn't agree with politics of data handling by a given processor and request to change processors or delete account.

**Comment by fjcero** [comment]
Checking, I supposed this was merged 😬
