### ISSUE TITLE
Can't add a processor without scopes

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#339]
**Describe the bug**
Adding a processor without scopes throw an error.

**To Reproduce**
1. Go to processors.
2. Click **+ Add processor**.
3. Fill in all data, but leave all scopes unchecked.
3. Hit Save.

**Expected behavior**
We should be able to add a processor without scopes (it should use default ones). @sindelio Please complete or modify if you have more informations.

**Screenshots**
![screen shot 2018-07-19 at 16 09 00](https://user-images.githubusercontent.com/1215868/42947799-6245c716-8b6e-11e8-8ff9-6f3d6bbea3cf.png)

**Additional context**
None.

**Comment by Nelrohd** [comment]
@sindelio From the demo we had last week, it seems to be back-end issue. Can you please confirm here and change the label if it's the case?

**Comment by segoddnja** [comment]
@Nelrohd This is not backend issue, this is a bug in the Admin frontend application, actually it is one minute fix. But, bu itself it leads to other questions. Do we really need these scopes? How can Controller which adopts ClearGDPR manage these scopes? What if Controller collects different types of data from different Subjects? Example is HR company - it collects data from employees and from employers.
