### ISSUE TITLE
Discuss how different domains should interact with each other

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#347]
**Is your feature request related to a problem? Please describe.**
@sindelio please complete if you get more informations.

**Describe the solution you'd like**
Doing some research and having a discussion to offer the best output. @sindelio Please complete or modify if you get more informations.

**Describe alternatives you've considered**
None.

**Additional context**
In case 2 domains have the same code, should we leave both with the repeating code, or should we create a shared domain for that repeating code, or maybe something else?

**Comment by segoddnja** [comment]
@sindelio Can you provide an example? Btw 'domains', are we talking in terms of DDD?

**Comment by sindelio** [comment]
This is not relevant anymore
