### ISSUE TITLE
Refactor the processor listeners for more clarity

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#350]
**Is your feature request related to a problem? Please describe.**
The current pattern for the processor listeners is a little confusing.

**Describe the solution you'd like**
Implementing a simpler pattern for listeners. @sindelio please complete if you get more informations.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sindelio** [comment]
Consider implementing a simpler pattern for the listeners, as they are a little complex right now

**Comment by segoddnja** [comment]
@sindelio I checked the `cg/src/domains/processors/processors.listeners.js` code, didn't notice any problems. It's only 75 LOC and is pretty clear, it just imports few methods to assign listeners to events and uses them.

But, I would cover by tests. And right now it is not so easy to do. I would do next:
1. Extract all event binders from `cg/src/utils/blockchain.js` into class. This class should receive `quorumContract` and `winston` dependencies in constructor. So, it would be easy to cover this class just passing mock instances to constructor.
2. Convert `cg/src/domains/processors/processors.listeners.js` from a list of functions to class. This class should receive instance of class from 1 as dependency. Cover it by tests.

What do you think?

**Comment by Nelrohd** [comment]
@segoddnja 
https://github.com/ClearGDPR/ClearGDPR/blob/master/cg/src/domains/processors/processors.listeners.js#L29 We should use try/catch for example

**Comment by sindelio** [comment]
Creating a separate class for the listeners sounds like a good idea. Though the requests made in cg/src/domains/processors/processors.requests.js need to make those API calls to the controller, so I think it's better to leave the requests as they are for now because we would be adding code to the processors controller and service without really need for it.
The goal here was to make sure @segoddnja  understand how the smart-contract events work in order to create the event auditing tool for the managers. I think we got it, so let's get back to that event auditing tool for the managers. We can refactor the processors listeners after that.
I didn't understand the comment about try/catch, can you elaborate @segoddnja ?

**Comment by segoddnja** [comment]
Close it because it is unclear will we need this feature in future or not.
