### ISSUE TITLE
Add endpoint for blockchain events

### ISSUE THREAD

**Issue by Nelrohd** [ClearGDPR/ClearGDPR#361]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Implement an endpoint to fetch blockchain events.

**Describe alternatives you've considered**
No.

**Additional context**
Blocking #320.

**Comment by segoddnja** [comment]
Let me summarize current state of project. All events are inside blockchain, it is possible only to get plain list of past events without ability to filter or aggregate it. So, if we need to do any reporting against events or just to filter events to display some certain event type - the only way to do it is to fetch ALL events and do processing from application.

The possible solution is to use Domain Events, especially as we are trying to follow DDD implementing backend. So, application can listen to the blockchain events and write proper Domain Events to the database. This will give us much more flexibility to work with events.

I understand that it would be better not do this, so, if there is a way to do filtering and aggregation on the blockchain side it would be great.

**Comment by segoddnja** [comment]
As we decided to implement only real time events flow, this task is not necessary to do now.
If we decide to implement past events listing feature we will re-open it.
