### ISSUE TITLE
Right to objection of processing

### ISSUE THREAD

**Issue by fjcero** [ClearGDPR/ClearGDPR#368]
**Is your feature request related to a problem? Please describe.**
Allow the Subject to object processing to the controller or certain processor

Ref. Article: https://gdpr-info.eu/art-21-gdpr/

**Describe the solution you'd like**
Create a new Element SDK component that renders a way to allow the Subject to prevent processing of data. For now just closing the loop will be enough, no need to address to much granularity control.

The endpoints used for Objection are:
- `/api/subject/get-objection`
- `/api/subject/object`

**Additional context**
No design provided, so first, we should address interaction and then some styling

**Comment by segoddnja** [comment]
I think we can make this element simple switch with label like this http://pix.toile-libre.org/upload/original/1533653901.png @juanmnl Is it something you can add style quickly? It should be just switch with label.
