### ISSUE TITLE
Attempt a private transaction with a local quorum cluster

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#4]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Wednesday Apr 11, 2018 at 11:06 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/36_

----

Now that we have quorum working locally we should attempt a private transaction between 2 nodes in a 3 node setup. We should use web3js and the test should attempt to read the consent status from the blockchain on both nodes: one that is privy to the transaction and one that is not privy to the transaction.

Useful example is included here:
https://github.com/ConsenSys/quorum-docker-Nnodes/blob/master/Nnodes/templates/contract_pri.js

**Comment by Jakedavies** [comment]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Wednesday May 02, 2018 at 20:17 GMT_

----

I don't think so, I think we should attempt it at some point in the future.

**Comment by Jakedavies** [comment]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sindelio](https://github.com/sindelio)**
_Thursday May 03, 2018 at 21:42 GMT_

----

I can work in this when the time comes

**Comment by sindelio** [comment]
Why was this task closed?
