### ISSUE TITLE
Updating the architecture diagram

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#41]
Possible changes:

[done] CG Controller Node 2 => CG Processor Node 2
[done] GDPR Actions Inovactions / payloads to encrypt & store => GDPR action invocations
[done] Blockchain contract writes => Smart Contract state update or Smart Contract function invocation
[done] User facing site => www.times.com
[too long and unnecessary]  Syncs user data when Blockchain notifies of updates to state => Syncs user data when Quorum Node notifies of updates to the Blockchain state
[unnecessary] Blockchain state Sync => Smart Contract state sync
[unnecessary] Blockchain Events => Smart Contract events
[unnecessary] The Quorum Blockchain is in the middle in a separate box, but in reality it's inside the Quorum Nodes, each with a copy

**Comment by Jakedavies** [comment]
@juanmnl can we do 1. and 4. asap

**Comment by juanmnl** [comment]
~~1. CG Controller Node 2 => CG Processor Node 2~~
~~2. GDPR Actions Inovactions / payloads to encrypt & store => GDPR action invocations~~
~~3. Blockchain contract writes => Smart Contract state update or Smart Contract function invocation~~
~~4. User facing site => Sport Times or Web Times~~
5. Syncs user data when Blockchain notifies of updates to state => Syncs user data when Quorum Node notifies of updates to the Smart Contract state
6. Blockchain Sync => Smart Contract state sync
7. Blockchain Events => Smart Contract events
8. The Quorum Blockchain is in the middle in a separate box, but in reality it's inside the Quorum Nodes, each with a copy

![diagram-fixes](https://user-images.githubusercontent.com/699945/40729885-01a0cfc0-63f3-11e8-86d0-a913158e226b.png)

**Comment by sindelio** [comment]
Now we just gotta think about the last possible change
