### ISSUE TITLE
Interactive quick start script

### ISSUE THREAD

**Issue by maksymilian-majer** [ClearGDPR/ClearGDPR#42]
The Quick Start guide can be mostly converted into a wizard like interactive shell script and generate the right config, .env files, docker-compose settings, etc.

Relates to #24

**Comment by maksymilian-majer** [comment]
We can use [oclif](https://oclif.io) or its [components](https://github.com/oclif/cli-ux) to create nice looking prompts and flow.

**Comment by Jakedavies** [comment]
I have implemented this in a fairly basic way with pure node (in an effort to reduce dependencies), its basically done and I _think_ it is all working, but I haven't been able to actually get the project to start up properly after running the script.

The error is from the geth nodes:
```
Fatal: failed to find local enode ID (3527544612c47a3c341a8fed0f4768e415540103ad157cc90438670e96bd814cb161ffaee6ab94560466f16942cc3ab5f528311a9440d3959cf5ace667d8d72a) amongst peer IDs: [5fc5d18c59dc3be404a6ed033d4423fb0cc78b1b5edcb069921d5f0a2b8c639e966ae587852dcb47250d69e1863c8b78763e31a9b9c7506e9ebda2ba29af7570 4cb0e3695bc0ce70b1a737c0e745af0544180921f4c3978e7f0de820a16d89ffc9dcf541f76ad9485e6b15522e521af9bc9fd491c9f649967285859746eb0ce2]
```

I spent some time debugging it today but wasn't able to work out what was messed up, but I will chat with you @maksymilian-majer tomorrow and see if you have any thoughts. I know I had similar issues when following the manual quick start guide.

**Comment by Jakedavies** [comment]
Note: Update quick start to tell you to run this script instead of the manual steps

**Comment by maksymilian-majer** [comment]
@Jakedavies and maybe add a package.json script instead of `node setup.js`?
