### ISSUE TITLE
Clean the database tables

### ISSUE THREAD

**Issue by sindelio** [ClearGDPR/ClearGDPR#420]
**Is your feature request related to a problem? Please describe.**
It's a refactor

**Describe the solution you'd like**
The database tables are outdated and bloated. A clean up there would be nice.
For instance:

- Subject restrictions and objection states could be in the 'subjects' table, without 2 extra migrations
- 'processor_address' table will be merged to 'processors' table
- The cascade delete migration will be updated

**Describe alternatives you've considered**
We can leave as it is, it's working for now. This is low priority, but would be nice

**Additional context**
Let me do it, because it depends on the processors setup

**Comment by Nelrohd** [comment]
Using https://www.quickdatabasediagrams.com/faq.html
```
config
-
key PK varchar(255)
value jsonb

data_shares
-
id PK int autoincrement
name varchar(255)
token varchar(255)
subject_id varchar(255) FK >- subjects.id

processor_address
-
processor_id int PK FK >- processors.id
address varchar(42) NULL

processors
-
id PK int
name varchar(255)
logoUrl varchar(255) NULL
description TEXT NULL
scopes jsonb NULL

rectification_requests
- 
id PK int autoincrement
subject_id varchar(255) FK >- subjects.id
request_reason varchar(255) NULL
encrypted_rectification_payload TEXT NULL
created_at timestamptz NULL default=CURRENT_TIMESTAMP
status text NULL

subject_keys
-
subject_id PK varchar(255) FK >- subjects.id
created_at timestamptz NULL default=CURRENT_TIMESTAMP
updated_at timestamptz NULL default=CURRENT_TIMESTAMP
key varchar(255)

subject_processors
-
subject_id PK varchar(255) FK >- subjects.id
processor_id PK int FK >- processors.id


subjects
-
id PK varchar(255)
created_at timestamptz NULL default=CURRENT_TIMESTAMP
updated_at timestamptz NULL default=CURRENT_TIMESTAMP
personal_data text
direct_marketing boolean default=false
email_communication boolean default=false
research boolean default=false
objection boolean default=false

users
-
id PK int autoincrement
username varchar(255)
password_hash varchar(255)
```

Image of the database diagram
![quickdbd-cleargdpr 3](https://user-images.githubusercontent.com/1664480/44646476-48ef4980-aa05-11e8-9a73-f9c4073241de.png)
