### ISSUE TITLE
Keep the smart contract state across different deployments

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#5]
**Is your feature request related to a problem? Please describe.**
If we need to update the smart contract inside the Quorum network for any reason, such as fixing a bug or updating its functionalities, then we will need to import it's state (variable values) to the new contract.

**Describe the solution you'd like**
To complete... @sindelio maybe?

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Jakedavies** [comment]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sindelio](https://github.com/sindelio)**
_Thursday Apr 12, 2018 at 14:54 GMT_

----

When we update a private smart contract inside a Quorum network, we will want to keep it's state, as we can't simply throw away what happened in the past. Also, if we find a problem and need to change the smart contract, same goes. I can look into that

**Comment by Jakedavies** [comment]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sindelio](https://github.com/sindelio)**
_Sunday Apr 15, 2018 at 21:28 GMT_

----

Found good material on this!
Will update when I have value to add

**Comment by sindelio** [comment]
There's ongoing work on making it possible to add nodes to private smart-contracts after it was deployed. So this won't be necessary in the future. Also, we're moving with a public smart-contract in a private network, so this won't be necessary for now
