### ISSUE TITLE
Sometimes app crashes due to node-scrypt

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#6]
<a href="https://github.com/maksymilian-majer"><img src="https://avatars2.githubusercontent.com/u/1215868?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [maksymilian-majer](https://github.com/maksymilian-majer)**
_Thursday Apr 12, 2018 at 19:46 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/51_

----

<img width="891" alt="screen shot 2018-04-12 at 21 43 09" src="https://user-images.githubusercontent.com/1215868/38700213-9d1c9f52-3e9a-11e8-9403-619762da4bd0.png">

Some related issues:
barrysteyn/node-scrypt/issues/150
barrysteyn/node-scrypt/issues/148

Not sure that it's fixed in `node-scrypt`.

**Comment by Jakedavies** [comment]
@maksymilian-majer is this still an issue?

**Comment by maksymilian-majer** [comment]
@Jakedavies It is for me. If I switch branches. This may be due to difference in yarn packages between branches.

**Comment by Nelrohd** [comment]
@sindelio It seems fixed in #11 . Please re-open if it's not.
