### ISSUE TITLE
Build an interface for creating/managing users data sharing URL's

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#78]
This is part of #25 
We need a UI where subjects can do the following.

- Create "share urls"(I think just a url with a unique token on it) and name the share url.
- See all existing share urls
- Delete existing share urls

**Comment by juanmnl** [comment]
@Jakedavies can you give me an example of how the url could look, pls 😄

**Comment by maksymilian-majer** [comment]
How about: `https://cg-demo.cleargdpr.com/shares/B6FQ3WG5AZ9`?

Basically the part: `https://cg-demo.cleargdpr.com`will be dependent on an implementation.
Say a company named bigdata has CG deployed at `https://gdpr.bigdata.com`, then the URL will be something like `https://cg-demo.cleargdpr.com/shares/K4I8RGA5A8U`.

**Comment by juanmnl** [comment]
Concept: https://invis.io/S6M0TLGNEHV#/305747169_data_Portability

**Comment by Jakedavies** [comment]
:+1:
