### ISSUE TITLE
Write integration/unit tests for the smart contract

### ISSUE THREAD

**Issue by Jakedavies** [ClearGDPR/ClearGDPR#9]
<a href="https://github.com/sindelio"><img src="https://avatars1.githubusercontent.com/u/19046387?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sindelio](https://github.com/sindelio)**
_Monday Apr 23, 2018 at 15:17 GMT_
_Originally opened as https://github.com/clevertech/OpenGDPR/issues/86_

----

Since we will have more iterations on the smart contract, writing tests will probably spare us time in the future

**Comment by sindelio** [comment]
If we ever need to isolate the smart contract functions, use the blockchain-function-test.js file in the scripts folder. Anyways, we are testing the smart contract functions together with the db and everything else, in E2E tests, so this is not relevant anymore
